site_name: Miko Tech Tips
site_url: https://miko.us.kg
nav:
  - 主页:
    - index.md
    - 开坑计划: todo.md
  - 编程:
    # - coding/index.md
    - C#:
      - coding/csharp/index.md
  - 游戏开发:
    - Unity:
      - gamedev/unity/index.md
  - 工具箱:
      - Mkdocs语法:
        - Admonitions - 提示: toolbox/mkdocs/admonitions.md
        - Annotations - 注释: toolbox/mkdocs/annotations.md
        - Code blocks - 代码块: toolbox/mkdocs/codeblocks.md
        - Footnotes - 脚注: toolbox/mkdocs/footnotes.md
        - Tooltips - 悬浮提示: toolbox/mkdocs/tooltips.md
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search
    - search.suggest
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换到亮色模式
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到暗色模式
copyright: Copyright &copy; 2024 - 2025 MikoTechTips
extra:
  social:
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/bubblesnewway
    - icon: fontawesome/brands/github
      link: https://github.com/miko-cn
    - icon: fontawesome/solid/envelope
      link: mailto:mikott@foxmail.com
  consent:
    title: Cookie 使用许可
    description: >- 
      本站使用cookies来识别您的重复访问偏好、提供反馈渠道，以及衡量文档的有效性以及用户是否找到了他们正在搜索的内容。在您的同意下，您正帮助本站使文档变得更好。
  analytics: 
    feedback:
      title: 这篇文章有帮助到你吗？
      ratings:
        - icon: material/thumb-up-outline
          name: 太赞啦！继续加油！
          data: 1
          note: >-
            感谢你的反馈！
        - icon: material/thumb-down-outline
          name: 还有提高的空间。
          data: 0
          note: >- 
            感谢你的批评！<br>提交反馈或建议请到：<a href="https://github.com/miko-cn/miko-cn.github.io/issues/new/?title=[反馈]+{title}+-+{url}" target="_blank" rel="noopener">Github Issues</a>.
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - scripts/feedback.js