site_name: Miko Tech Tips
site_url: https://miko.us.kg
nav:
  - 主页: index.md
  - 编程:
    - coding/index.md
    - C/C++:
      - coding/c-cpp/index.md
    - C#:
      - coding/csharp/index.md
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search
    - search.suggest
    - header.autohide
    - content.code.copy
    - content.code.annotate
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换到亮色模式
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到暗色模式
copyright: Copyright &copy; 2024 - 2025 MikoTechTips
extra:
  social:
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/bubblesnewway
    - icon: fontawesome/brands/github
      link: https://github.com/miko-cn
    - icon: fontawesome/solid/envelope
      link: mailto:mikott@foxmail.com
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true